name: IPFS Filebase

on: workflow_dispatch
#on: [push]

jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: alexanderschau/ipfs-pinning-action@v1.1.0
      with:
        path_to_add: '/' 
        endpoint: 'https://api.filebase.io/v1/ipfs/pins'
        access_token: ${{ secrets.FILEBASE_SECRET_KEY }} 
        pin_name: 'otk-data'
