name: IPFS

on: [push,workflow_dispatch]
#on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: aquiladev/ipfs-action@master
      id: upload_
      with:
        path: ./exp
        service: filebase
        pinName: 'otk-data'
        filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
        filebaseKey: ${{ secrets.FILEBASE_KEY }}
        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

    - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      id: upload
      with:
        pin-name: 'otk-data'
        path: './exp'
        pinata-api-key: ${{ secrets.PINATA_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
        verbose: false
        remove-old: true
        
    - run: curl -H "Content-Type:application/json" -H "apikey:${{ secrets.FREEDOMAIN_API_KEY }}" -H "domain:${{ secrets.FREEDOMAIN_DOMAIN }}" --data "{\"update\":{\"type\":\"TXT\",\"name\":\"_dnslink.otk-data.publicvm.com.\",\"content\":\"dnslink=/ipfs/${{ steps.upload.outputs.hash }}\",\"ttl\":0,\"overwrite\":true}}" https://api.dnsexit.com/dns/
