name: IPFS 2

on: workflow_dispatch
#on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
  
#    - run: npm ci
  
#    - run: npm run build

    - uses: aquiladev/ipfs-action@master
      with:
        path: ./
        service: filebase
        pinName: 'ipfs-action'
        filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
        filebaseKey: ${{ secrets.FILEBASE_KEY }}
        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

    - uses: aquiladev/ipfs-action@master
      with:
        path: ./
        service: pinata
        pinataKey: ${{ secrets.PINATA_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET }}
