name: Deploy to Orbiter

on: workflow_dispatch
#on:
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Deploy to Orbiter
        shell: bash
        env:
          ORBITER_API_KEY: ${{ secrets.ORBITER_API_KEY }} # Will use repository secret
        run: npx orbiter-cli update -d "otk-data" "./exp"
